# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 14:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0002_documentosexcel_documentosgoogle'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosgoogle',
            name='nombre_analisis',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 41, 51, 964671)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 41, 51, 962964)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
