# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0004_auto_20180123_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosexcel',
            name='nombre_analisis',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 52, 5, 736742)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 52, 5, 735498)),
        ),
    ]
