# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 14:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptwitter', '0005_auto_20180123_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoExcel',
            fields=[
                ('id_documentoexcel', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 52, 47, 778568))),
                ('archivo', models.FileField(blank=True, upload_to='archivos')),
                ('nombre_analisis', models.CharField(max_length=250, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGoogle',
            fields=[
                ('id_documentogoogle', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 9, 52, 47, 777658))),
                ('archivo_key', models.CharField(max_length=450)),
                ('nombre_analisis', models.CharField(max_length=250, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentosexcel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='documentosgoogle',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DocumentosExcel',
        ),
        migrations.DeleteModel(
            name='DocumentosGoogle',
        ),
    ]
