# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptwitter', '0012_auto_20180123_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosExcel',
            fields=[
                ('id_documentoexcel', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 10, 21, 48, 515161))),
                ('archivo', models.FileField(blank=True, upload_to='archivos')),
                ('nombre_analisis', models.CharField(max_length=450)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosGoogle',
            fields=[
                ('id_documentogoogle', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 10, 21, 48, 514129))),
                ('archivo_key', models.CharField(max_length=450)),
                ('nombre_analisis', models.CharField(max_length=450)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentoexcel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='documentogoogle',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DocumentoExcel',
        ),
        migrations.DeleteModel(
            name='DocumentoGoogle',
        ),
    ]
