# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0013_auto_20180123_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 10, 22, 3, 494620)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 10, 22, 3, 493701)),
        ),
    ]
