# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0015_auto_20180123_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisAnteriores',
            fields=[
                ('id_analisisanteriores', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_analisis', models.DateTimeField(default=datetime.datetime(2018, 1, 24, 18, 51, 9, 26187))),
                ('direccion_documento', models.CharField(max_length=550)),
            ],
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 18, 51, 9, 24828)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 18, 51, 9, 23803)),
        ),
        migrations.AddField(
            model_name='analisisanteriores',
            name='documentogoogle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apptwitter.DocumentosGoogle'),
        ),
    ]
