# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0016_auto_20180124_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosgoogle',
            name='nombre_analisis',
        ),
        migrations.AddField(
            model_name='analisisanteriores',
            name='nombre_analisis',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='analisisanteriores',
            name='fecha_analisis',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 27, 38, 857652)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 27, 38, 855854)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 27, 38, 854555)),
        ),
    ]
