# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0017_auto_20180124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosgoogle',
            name='nombre_analisis',
            field=models.CharField(default='', max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='analisisanteriores',
            name='fecha_analisis',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 30, 17, 615971)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 30, 17, 614247)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 30, 17, 612989)),
        ),
    ]
