# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0018_auto_20180124_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosgoogle',
            name='nombre_analisis',
        ),
        migrations.AlterField(
            model_name='analisisanteriores',
            name='fecha_analisis',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 31, 59, 908773)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 31, 59, 907632)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 31, 59, 906748)),
        ),
    ]
