# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0020_auto_20180124_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosgoogle',
            name='nombre_archivo',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='analisisanteriores',
            name='fecha_analisis',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 57, 35, 53541)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 57, 35, 51017)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 19, 57, 35, 49360)),
        ),
    ]
