# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwitter', '0021_auto_20180124_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisanteriores',
            name='fecha_analisis',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 20, 20, 270958)),
        ),
        migrations.AlterField(
            model_name='documentosexcel',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 20, 20, 270253)),
        ),
        migrations.AlterField(
            model_name='documentosgoogle',
            name='fechaingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 15, 21, 20, 20, 269681)),
        ),
    ]
